# Generated by Django 6.0.1 on 2026-02-28 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMCQResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, help_text='Raw MCQ answers as JSON')),
                ('category', models.CharField(choices=[('anxiety', 'Anxiety'), ('depression', 'Depression'), ('stress', 'Stress'), ('ptsd', 'PTSD'), ('general', 'General Wellness')], default='general', max_length=30)),
                ('score', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Patient MCQ Result',
            },
        ),
        migrations.RemoveIndex(
            model_name='adminreport',
            name='accounts_ad_report__8308a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='adminreport',
            name='accounts_ad_is_reso_9a0c5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='accounts_ap_patient_16454f_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='accounts_ap_therapi_06fd20_idx',
        ),
        migrations.RemoveField(
            model_name='review',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='assessmentchoice',
            name='question',
        ),
        migrations.RemoveIndex(
            model_name='chatlog',
            name='accounts_ch_user_id_af607e_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatlog',
            name='accounts_ch_crisis__a1fd0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='externalevent',
            name='accounts_ex_event_d_679996_idx',
        ),
        migrations.DeleteModel(
            name='ExternalEvent',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='accounts_no_user_id_a4ff2e_idx',
        ),
        migrations.RemoveIndex(
            model_name='patientanswer',
            name='accounts_pa_assessm_debf34_idx',
        ),
        migrations.RemoveConstraint(
            model_name='patientanswer',
            name='unique_assessment_question',
        ),
        migrations.RemoveIndex(
            model_name='patientassessment',
            name='accounts_pa_patient_bdad36_idx',
        ),
        migrations.RemoveIndex(
            model_name='patientprofile',
            name='accounts_pa_recomme_d616ee_idx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='therapistavailability',
            name='accounts_th_therapi_c8679f_idx',
        ),
        migrations.RemoveConstraint(
            model_name='therapistavailability',
            name='unique_therapist_slot',
        ),
        migrations.RemoveIndex(
            model_name='therapistprofile',
            name='accounts_th_special_35c11d_idx',
        ),
        migrations.RemoveIndex(
            model_name='therapistprofile',
            name='accounts_th_therapi_f48896_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='accounts_cu_role_666d59_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='accounts_cu_email_5ce40b_idx',
        ),
        migrations.AddField(
            model_name='patientmcqresult',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_result', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='adminreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='therapist',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patientanswer',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='patientanswer',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='patientanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='patientassessment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='profile_ptr',
        ),
        migrations.RemoveField(
            model_name='therapistavailability',
            name='therapist',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='profile_ptr',
        ),
        migrations.DeleteModel(
            name='AdminReport',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='ChatLog',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='AssessmentChoice',
        ),
        migrations.DeleteModel(
            name='AssessmentQuestion',
        ),
        migrations.DeleteModel(
            name='PatientAnswer',
        ),
        migrations.DeleteModel(
            name='PatientAssessment',
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
        migrations.DeleteModel(
            name='TherapistAvailability',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='TherapistProfile',
        ),
    ]
