# Generated by Django 6.0.1 on 2026-02-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patientmcqresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(blank=True, choices=[('', 'None'), ('anxiety', 'Anxiety Disorders'), ('depression', 'Depression Treatment'), ('stress', 'Stress Management'), ('ptsd', 'Trauma & PTSD'), ('general', 'General Wellness'), ('addiction', 'Addiction Counseling'), ('family', 'Family Therapy')], default='', help_text='Therapist specialization (only for doctors)', max_length=30),
        ),
    ]
