# Generated by Django 6.0.1 on 2026-02-28 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_guidedexercise_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('rejected', 'Rejected')], default='requested', max_length=20),
        ),
        migrations.CreateModel(
            name='TherapistDayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Therapist Day Off',
                'verbose_name_plural': 'Therapist Days Off',
                'ordering': ['date'],
                'unique_together': {('therapist', 'date')},
            },
        ),
    ]
