# Generated by Django 6.0.2 on 2026-02-28 21:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_appointment_status_therapistdayoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('task', 'Daily Task'), ('challenge', 'Fun Challenge'), ('mood', 'Mood Check-in')], max_length=20)),
                ('title', models.CharField(help_text='Task/Challenge name or mood type', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('mood', models.CharField(blank=True, choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('low', 'Low'), ('struggling', 'Struggling')], max_length=20)),
                ('points', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'ordering': ['-created_at'],
            },
        ),
    ]
