# Generated by Django 6.0.2 on 2026-02-28 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirect_url',
            field=models.CharField(blank=True, default='', help_text='URL to redirect when clicked', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment_requested', 'Appointment Requested'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_rescheduled', 'Appointment Rescheduled'), ('appointment_rejected', 'Appointment Rejected'), ('report_uploaded', 'Session Report Uploaded'), ('message', 'New Message'), ('system', 'System Notification')], max_length=30),
        ),
        migrations.CreateModel(
            name='TherapistRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating 1-5 stars')),
                ('review', models.TextField(blank=True, help_text='Optional review text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='accounts.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Therapist Rating',
                'ordering': ['-created_at'],
            },
        ),
    ]
