# Generated by Django 6.0.2 on 2026-03-01 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notification_redirect_url_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('clicked_video_id', models.CharField(blank=True, help_text='Video ID if user clicked a result', max_length=255)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoWatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(help_text='YouTube video ID or resource ID', max_length=255)),
                ('video_title', models.CharField(max_length=255)),
                ('video_source', models.CharField(choices=[('youtube', 'YouTube'), ('database', 'Database Resource')], default='youtube', max_length=20)),
                ('category', models.CharField(help_text='meditation, yoga, breathing, etc.', max_length=50)),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('watch_duration', models.PositiveIntegerField(default=0, help_text='Seconds watched')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Watch History',
                'ordering': ['-watched_at'],
            },
        ),
    ]
