# Generated by Django 6.0.1 on 2026-03-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_searchhistory_videowatchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resource_type',
        ),
        migrations.AlterField(
            model_name='resource',
            name='video_url',
            field=models.URLField(help_text='YouTube embed URL, e.g. https://www.youtube.com/embed/VIDEO_ID'),
        ),
    ]
