# Generated by Django 6.0.1 on 2026-03-13 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_aichatsession_user_chatsession_chatmessage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videowatchhistory',
            options={},
        ),
        migrations.RemoveField(
            model_name='videowatchhistory',
            name='watch_duration',
        ),
        migrations.AlterField(
            model_name='videowatchhistory',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videowatchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videowatchhistory',
            name='video_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videowatchhistory',
            name='video_source',
            field=models.CharField(default='youtube', max_length=50),
        ),
    ]
