# Generated by Django 6.0.1 on 2026-04-03 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_appointment_payment_refund_and_payout'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('anxiety', 'Anxiety'), ('depression', 'Depression'), ('stress', 'Stress'), ('ptsd', 'PTSD'), ('general', 'General Wellness')], default='general', max_length=30)),
                ('exercise_type', models.CharField(choices=[('breathing', 'Breathing Exercise'), ('meditation', 'Guided Meditation'), ('relaxation', 'Progressive Relaxation'), ('journaling', 'Journaling Prompt'), ('grounding', 'Grounding Technique'), ('mindfulness', 'Mindfulness Exercise')], default='breathing', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15)),
                ('steps', models.JSONField(default=list, help_text='Ordered list of step strings')),
                ('duration_minutes', models.PositiveIntegerField(default=5)),
                ('icon', models.CharField(default='🧘', help_text='Emoji icon', max_length=10)),
                ('video_url', models.URLField(blank=True, help_text='Optional YouTube embed URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Guided Exercise',
                'ordering': ['category', 'exercise_type'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(default='card', max_length=20),
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('clicked_video_id', models.CharField(blank=True, help_text='Video ID if user clicked a result', max_length=255)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'ordering': ['-searched_at'],
            },
        ),
    ]
