# Generated by Django 6.0.1 on 2026-03-20 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_is_verified_customuser_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_therapists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('therapist', 'Therapist'), ('admin', 'Admin')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(blank=True, choices=[('', 'None'), ('anxiety', 'Anxiety Disorders'), ('depression', 'Depression Treatment'), ('stress', 'Stress Management'), ('ptsd', 'Trauma & PTSD'), ('general', 'General Wellness'), ('addiction', 'Addiction Counseling'), ('family', 'Family Therapy')], default='', help_text='Therapist specialization (only for therapists)', max_length=30),
        ),
    ]
