# Generated by Django 6.0.1 on 2026-04-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_guidedexercise_customuser_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='program_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='program_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='program_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='program_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientmcqresult',
            name='category',
            field=models.CharField(choices=[('anxiety', 'Anxiety'), ('depression', 'Depression'), ('stress', 'Stress'), ('ptsd', 'Trauma & PTSD'), ('general', 'General Wellness'), ('addiction', 'Addiction'), ('family', 'Family Issues')], default='general', max_length=30),
        ),
    ]
