# Generated by Django 6.0.1 on 2026-03-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_customuser_approved_by_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_approved',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rejection_reason',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(blank=True, choices=[('', 'None'), ('anxiety', 'Anxiety Disorders'), ('depression', 'Depression Treatment'), ('stress', 'Stress Management'), ('ptsd', 'Trauma & PTSD'), ('general', 'General Wellness'), ('addiction', 'Addiction Counseling'), ('family', 'Family Therapy')], default='', help_text='Therapist specialization (only for doctors)', max_length=30),
        ),
    ]
