# Generated by Django 6.0.1 on 2026-04-06 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_notification_program_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineAwarenessProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_awareness_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Online Awareness Program',
                'verbose_name_plural': 'Online Awareness Programs',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
