# Generated by Copilot to add post-login terms acceptance tracking.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]