# Generated by Django 6.0.1 on 2026-04-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(blank=True, choices=[('', 'None'), ('anxiety', 'Anxiety Disorders'), ('depression', 'Depression Treatment'), ('stress', 'Stress Management'), ('ptsd', 'Trauma & PTSD'), ('general', 'General Wellness'), ('addiction', 'Addiction Counseling'), ('family', 'Family Therapy')], default='', help_text='Therapist specialization (only for therapists)', max_length=30),
        ),
    ]
